// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Image struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Image     string    `json:"image"`
	Enabled   bool      `json:"enabled"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Score struct {
	ID          int64     `json:"id"`
	GameBanner  string    `json:"game_banner"`
	GameName    string    `json:"game_name"`
	PlayerName  string    `json:"player_name"`
	PlayerScore int64     `json:"player_score"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Session struct {
	Token  string  `json:"token"`
	Data   []byte  `json:"data"`
	Expiry float64 `json:"expiry"`
}

type User struct {
	ID                 int64     `json:"id"`
	Username           string    `json:"username"`
	PasswordHash       string    `json:"password_hash"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
	ForcePasswordReset bool      `json:"force_password_reset"`
}
