// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const createImage = `-- name: CreateImage :one
INSERT INTO images (name, image, enabled)
VALUES (?, ?, ?)
RETURNING id, name, image, enabled, created_at, updated_at
`

type CreateImageParams struct {
	Name    string `json:"name"`
	Image   string `json:"image"`
	Enabled bool   `json:"enabled"`
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (Image, error) {
	row := q.db.QueryRowContext(ctx, createImage, arg.Name, arg.Image, arg.Enabled)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Image,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createScore = `-- name: CreateScore :one
INSERT INTO scores (game_banner, game_name, player_name, player_score)
VALUES (?, ?, ?, ?)
RETURNING id, game_banner, game_name, player_name, player_score, created_at, updated_at
`

type CreateScoreParams struct {
	GameBanner  string `json:"game_banner"`
	GameName    string `json:"game_name"`
	PlayerName  string `json:"player_name"`
	PlayerScore int64  `json:"player_score"`
}

func (q *Queries) CreateScore(ctx context.Context, arg CreateScoreParams) (Score, error) {
	row := q.db.QueryRowContext(ctx, createScore,
		arg.GameBanner,
		arg.GameName,
		arg.PlayerName,
		arg.PlayerScore,
	)
	var i Score
	err := row.Scan(
		&i.ID,
		&i.GameBanner,
		&i.GameName,
		&i.PlayerName,
		&i.PlayerScore,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash)
VALUES (?, ?)
RETURNING id, username, password_hash, created_at, updated_at
`

type CreateUserParams struct {
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteImage = `-- name: DeleteImage :exec
DELETE FROM images WHERE id = ?
`

func (q *Queries) DeleteImage(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteImage, id)
	return err
}

const deleteScore = `-- name: DeleteScore :exec
DELETE FROM scores WHERE id = ?
`

func (q *Queries) DeleteScore(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteScore, id)
	return err
}

const getImage = `-- name: GetImage :one
SELECT id, name, image, enabled, created_at, updated_at FROM images WHERE id = ?
`

func (q *Queries) GetImage(ctx context.Context, id int64) (Image, error) {
	row := q.db.QueryRowContext(ctx, getImage, id)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Image,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScore = `-- name: GetScore :one
SELECT id, game_banner, game_name, player_name, player_score, created_at, updated_at FROM scores WHERE id = ?
`

func (q *Queries) GetScore(ctx context.Context, id int64) (Score, error) {
	row := q.db.QueryRowContext(ctx, getScore, id)
	var i Score
	err := row.Scan(
		&i.ID,
		&i.GameBanner,
		&i.GameName,
		&i.PlayerName,
		&i.PlayerScore,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, created_at, updated_at FROM users WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, created_at, updated_at FROM users WHERE username = ?
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledImages = `-- name: ListEnabledImages :many
SELECT id, name, image, enabled, created_at, updated_at FROM images WHERE enabled = TRUE ORDER BY name ASC
`

func (q *Queries) ListEnabledImages(ctx context.Context) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledImages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Image
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Image,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImages = `-- name: ListImages :many
SELECT id, name, image, enabled, created_at, updated_at FROM images ORDER BY name ASC
`

func (q *Queries) ListImages(ctx context.Context) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, listImages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Image
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Image,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScores = `-- name: ListScores :many
SELECT id, game_banner, game_name, player_name, player_score, created_at, updated_at FROM scores ORDER BY game_name ASC
`

func (q *Queries) ListScores(ctx context.Context) ([]Score, error) {
	rows, err := q.db.QueryContext(ctx, listScores)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Score
	for rows.Next() {
		var i Score
		if err := rows.Scan(
			&i.ID,
			&i.GameBanner,
			&i.GameName,
			&i.PlayerName,
			&i.PlayerScore,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, password_hash, created_at, updated_at FROM users ORDER BY username ASC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateImage = `-- name: UpdateImage :one
UPDATE images
SET name       = ?,
    image      = ?,
    enabled    = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
RETURNING id, name, image, enabled, created_at, updated_at
`

type UpdateImageParams struct {
	Name    string `json:"name"`
	Image   string `json:"image"`
	Enabled bool   `json:"enabled"`
	ID      int64  `json:"id"`
}

func (q *Queries) UpdateImage(ctx context.Context, arg UpdateImageParams) (Image, error) {
	row := q.db.QueryRowContext(ctx, updateImage,
		arg.Name,
		arg.Image,
		arg.Enabled,
		arg.ID,
	)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Image,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateScore = `-- name: UpdateScore :one
UPDATE scores
SET game_banner  = ?,
    game_name    = ?,
    player_name  = ?,
    player_score = ?,
    updated_at   = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
RETURNING id, game_banner, game_name, player_name, player_score, created_at, updated_at
`

type UpdateScoreParams struct {
	GameBanner  string `json:"game_banner"`
	GameName    string `json:"game_name"`
	PlayerName  string `json:"player_name"`
	PlayerScore int64  `json:"player_score"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdateScore(ctx context.Context, arg UpdateScoreParams) (Score, error) {
	row := q.db.QueryRowContext(ctx, updateScore,
		arg.GameBanner,
		arg.GameName,
		arg.PlayerName,
		arg.PlayerScore,
		arg.ID,
	)
	var i Score
	err := row.Scan(
		&i.ID,
		&i.GameBanner,
		&i.GameName,
		&i.PlayerName,
		&i.PlayerScore,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = ?,
    updated_at    = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

type UpdateUserPasswordParams struct {
	PasswordHash string `json:"password_hash"`
	ID           int64  `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	return err
}
